# CS225 Lab 1 - Intro to Python's Class & Object, Basic Datatypes Review

### Please scan the QR code to join the wechat group ↓

<img src='wc.jpg', width=180, height=200>

__<li>Recall your knowledge about python from CS101, what you were doing mostly at that time is called POP (Procedure Oriented Programming). Languages such as C language supports POP very well.</li>__

__<li>But features that python support is definitely more that that. One important concept when programming with python is called OOP (Object Oriented Programming), which is one of the core concepts in CS225, because it will facilitate your implementation of different data types and methods.</li>__

__<li>In this lab, we will introduce you to the class and Object in python language. Besides, we will do some review on the basic data types in python such as list, tuple, set and dictionary. You will find them useful when writing code in python.</li>__

### I. What is OOP specifically?

<li> POP deals with programs and functions and follows top down approach. Programs are divided into functions and data is global. </li>
<li> OOP deals with objects and their properties and follows bottom up approach. Programs are divided into objects and their interactions.</li>

#### What if you want put your best friend into a safe box?

<li> POP: open the safe box -> put my best friend into the safe box -> close the safe box</li>
<li> OOP: safe_box.open() -> my_best_friend.enter_safe_box() -> safe_box.close()</li>

### II. What is a class and what is an object?

<li> Python is an object oriented programming language. 
Almost everything in Python is an object, with its properties and methods. 
A Class is like an object constructor, or a "blueprint" for creating objects.</li>
<li>Objects are an encapsulation of variables and functions into a single entity. Objects get their variables and functions from classes. Classes are essentially a template to create your objects.</li>
<li>e.g. Human vs Individual</li>

### III. How do we deal with classes and objects in Python?

#### Create a Class  
<li>To create a class, use the keyword <b>class</b>:</li>

In [1]:
#Create a class named MyClass, with a property named x:
class MyClass:
    x = 5

#### Create Object
<li>Now we can use the class named <i>MyClass</i> to create objects:</li>

In [3]:
#Create an object named p1, and print the value of x:
p1 = MyClass()
print(p1.x) #field
p1.x = 6
print(p1.x) #field

5
6


#### The \_\_init\_\_() Function

<li>The examples above are classes and objects in their simplest form, and are not really useful in real life applications.

To understand the meaning of classes we have to understand the built-in \_\_init\_\_() function.

All classes have a function called \_\_init\_\_(), which is always executed when the class is being initiated.

Use the \_\_init\_\_() function to assign values to object properties, or other operations that are necessary to do when the object is being created:</li>

In [3]:
#Create a class named Person, use the __init__() function to assign values for name and age:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age)

John
36


#### Object Methods
<li>Objects can also contain methods. Methods in objects are functions that belong to the object.

Let us create a method in the <i>Person</i> class:</li>

In [4]:
#Insert a function that prints a greeting, and execute it on the p1 object:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def myfunc(self):
        print("Hello, my name is " + self.name)

p1 = Person("John", 36)
p1.myfunc()

Hello, my name is John


#### The self Parameter
<li>The <i>self</i> parameter is a reference to the current instance of the class, and is used to access variables that belongs to the class.
    
It does not have to be named <i>self</i>, you can call it whatever you like, but it has to be the first parameter of any function in the class:</li>

In [5]:
#Use the words mysillyobject and abc instead of self:
class Person:
    def __init__(mysillyobject, name, age):
        mysillyobject.name = name
        mysillyobject.age = age
    def myfunc(abc):
        print("Hello, my name is " + abc.name)

p1 = Person("John", 36)
p1.myfunc()

Hello, my name is John


#### Modify Object Properties
<li>You can modify properties on objects like this:</li>

In [6]:
print(p1.age)
p1.age = 40
print(p1.age)

36
40


#### Delete Object Properties
<li>You can delete properties on objects by using the <b>del</b> keyword:</li>

In [7]:
print(p1.age)
del p1.age
print(p1.age)  # Show that the properties is deleted at this point

40


AttributeError: 'Person' object has no attribute 'age'

#### Delete Objects
<li>You can delete objects by using the <b>del</b> keyword:</li>

In [4]:
print(p1)
del p1
print(p1)  # Show that the object is deleted at this point

NameError: name 'p1' is not defined

#### The pass Statement
<li>class definitions cannot be empty, but if you for some reason have a class definition with no content, put in the <b>pass</b> statement to avoid getting an error.</li>

In [10]:
class Person:
    x = 5

p1 = Person()
p1.y = 6
print(p1.y)

del p1.y

p1.y = 666
print(p1.y)

6
666


In [11]:
class Person:
    pass

## Review of Basic Data Types in Python (built-in classes in python)

### 1. List  
You can change the value, add or delete an item from a list.
##### Add Items:  
difference between **append()** and **extend()** and **insert()**. What do these functions return?

In [12]:
thislist = ["apple", "banana", "cherry"]
# Using the append() method to append an item in the end:
print(thislist.append("orange"))
print(thislist)

None
['apple', 'banana', 'cherry', 'orange']


In [13]:
# Use the extend() method to add list2 at the end of list1:
print(thislist.extend(['grapes']))
print(thislist)

None
['apple', 'banana', 'cherry', 'orange', 'grapes']


In [14]:
# Insert an item as the second position:
thislist = ["apple", "banana", "cherry"]
thislist.insert(1, "orange")
print(thislist)

['apple', 'orange', 'banana', 'cherry']


##### Remove Items:  

In [15]:
# The remove() method removes the specified item
thislist = ["apple", "banana", "cherry"]
thislist.remove("banana")
print(thislist)

['apple', 'cherry']


In [16]:
# The pop() method removes the specified index, (or the last item if index is not specified):
thislist = ["apple", "banana", "cherry"]
thislist.pop()
print(thislist)

['apple', 'banana']


In [19]:
thislist = ["apple", "banana", "cherry"]
print(thislist.pop(0))
print(thislist)

apple
['banana', 'cherry']


In [20]:
# The del keyword removes the specified index:
thislist = ["apple", "banana", "cherry"]
del thislist[0]
print(thislist)

['banana', 'cherry']


##### Join Two Lists

In [21]:
list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]
# Method 1:
list3 = list1 + list2
print(list3)
# Method 2:
list1.extend(list2)
print(list1)

['a', 'b', 'c', 1, 2, 3]
['a', 'b', 'c', 1, 2, 3]


<li> <b>Inherit</b> from the built-in list class to create our own pylist class</li>

In [80]:
class PyList(list):
    def __init__(self,contents=[],size=20):
        self.items = [None] * size
        self.numItems = 0
        self.size = size
        for e in contents:
            self.append(e)
            
    def __contains__(self,item):
        for i in range(self.numItems):
            if self.items[i] == item:
                return True
        return False

    def __eq__(self,other):
        if type(other) != type(self):
            return False
        if self.numItems != other.numItems:
            return False
        for i in range(self.numItems):
            if self.items[i] != other.items[i]:
                return False
        return True
    
    def __setitem__(self,index,val):
        if index >= 0 and index < self.numItems:
            self.items[index] = val
            return
        raise IndexError("PyList assignment index out of range")

    def __getitem__(self,index):
        if index >= 0 and index < self.numItems:
            return self.items[index]
        raise IndexError("PyList index out of range")
    
    def append(self,item):
        if self.numItems == self.size:
            self.allocate()
        self.items[self.numItems] = item
        self.numItems += 1
        
    def allocate(self):
        newlength = 2 * self.size
        newList = [None] * newlength
        for i in range(self.numItems):
            newList[i] = self.items[i]
        self.items = newList
        self.size = newlength
    
a = PyList([1,2,3,4],10)
b = PyList([1,2,3,4],10)
c = PyList([1,2,3,4],8)
d = PyList([1,2,3,4,5],10)
print(a.items)
print(a.numItems)
print(a.__eq__(b))
print(b.__eq__(c))
print(a.__eq__(d))

[]
asdsadasda
True
True
True
False


### 2. Tuple
Once a tuple is created, you **cannot change** its values. Tuples are **unchangeable**.  
You can convert the tuple into a **list**, change the list, and **convert** the list back into a tuple.

In [22]:
# will have an error
thistuple = ("apple", "banana", "cherry")
thistuple[3] = "orange" # This will raise an error
print(thistuple)

TypeError: 'tuple' object does not support item assignment

In [24]:
x = ("apple", "banana", "cherry")
y = list(x)
print(y)
y[1] = "kiwi"
x = tuple(y)

print(x)

['apple', 'banana', 'cherry']
('apple', 'kiwi', 'cherry')


**count()**: Returns the number of times a specified value occurs in a tuple.  
**index()**:  Searches the tuple for a specified value and returns the **first** position of where it was found.

In [27]:
x = (2,1,1,2,2,2,3)
print(x.count(2))
print(x.index(1))

4
1


### 3. Set
A set is a collection which is unordered and unindexed. In Python sets are written with curly brackets **{ }**.

In [28]:
# Check if "banana" is present in the set:
thisset = {"apple", "banana", "cherry"}
print("banana" in thisset)
print("peach" in thisset)

True
False


##### Add Items: 
Once a set is created, you **cannot change** its items, but you can **add** new items:

In [31]:
# Add an item to a set, using the add() method:

thisset = {"apple", "banana", "cherry"}

thisset.add("orange")

print(thisset)

{'apple', 'banana', 'orange', 'cherry'}


In [ ]:
# Add multiple items to a set, using the update() method:

thisset = {"apple", "banana", "cherry"}

thisset.update(["orange", "mango", "grapes"])

print(thisset)

##### Remove Items:   Methods remove(), discard(), or pop()

In [32]:
# Method 1 - Remove "banana" by using the remove() method:

thisset = {"apple", "banana", "cherry"}

thisset.remove("banana")

print(thisset)

# Method 2 - Remove "banana" by using the discard() method:

thisset.discard("apple")

print(thisset)

{'apple', 'cherry'}
{'cherry'}


You can also use the **pop()**, method to remove an item, but this method will remove the last item.

**Remember that sets are unordered, so you will not know what item that gets removed.**

The **return value** of the pop() method is the removed item.

In [33]:
# Method 3
thisset = {"apple", "banana", "cherry"}

x = thisset.pop()

print(x)

print(thisset)

apple
{'banana', 'cherry'}


##### Empty set:   Methods clear() or del keyword  
What is the difference between these two?

In [34]:
#The clear() method empties the set:

thisset = {"apple", "banana", "cherry"}

thisset.clear()

print(thisset)

set()


In [35]:
# The del keyword will delete the set completely:

thisset = {"apple", "banana", "cherry"}

del thisset

print(thisset)

NameError: name 'thisset' is not defined

##### Join two sets:   union() or update()
You can use the union() method that returns a new set containing all items from both sets, or the update() method that inserts all the items from one set into another. **Both union() and update() will exclude any duplicate items.**

In [36]:
# union method
set1 = {"a", "b" , "c"}
set2 = {"a",1, 2, 3}

set3 = set1.union(set2)
print(set3)

# update method
set1.update(set2)
print(set1)

{'c', 1, 2, 3, 'b', 'a'}
{'c', 1, 2, 3, 'b', 'a'}


##### intersection(), difference() of two sets

In [37]:
# intersection
set1 = {"a", "b" , "c"}
set2 = {"a",1, 2, 3}

set3 = set1.intersection(set2)
print(set3)

# difference
set1 = {"a", "b" , "c"}
set2 = {"a",1, 2, 3}

set3 = set1.difference(set2)
print(set3)

set3 = set2.difference(set1)
print(set3)

{'a'}
{'c', 'b'}
{1, 2, 3}


### 4.Dictionary
A dictionary is a collection which is **unordered, changeable and indexed**.   

In [38]:
# Create and print a dictionary:

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

# Another way to do that:
thisdict =	dict(brand="Ford", model="Mustang", year=1964)
# note that keywords are not string literals
# note the use of equals rather than colon for the assignment
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [39]:
# Get the value of the "model" key:
x = thisdict["model"]
print(x)

Mustang


In [40]:
# another way to do that:
x = thisdict.get("model")
print(x)

Mustang


In [41]:
# Change the "year" to 2018:

thisdict["year"] = 2018
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 2018}


In [45]:
# key, value and item
print(type(thisdict.keys()))
print(thisdict.values())
print(thisdict.items())

<class 'dict_keys'>
dict_values(['Ford', 'Mustang', 2018])
dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 2018)])


##### Add Items

In [46]:
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["color"] = "red"
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}


##### Remove Items: pop(), del keyword or clear()

In [51]:
# The pop() method removes the item with the specified key name:

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict.pop("model"))
print(thisdict)

Mustang
{'brand': 'Ford', 'year': 1964}


In [48]:
# The del keyword removes the item with the specified key name:

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
del thisdict["model"]
print(thisdict)

{'brand': 'Ford', 'year': 1964}


In [49]:
# The del keyword can also delete the dictionary completely:

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
del thisdict
print(thisdict) #this will cause an error because "thisdict" no longer exists.

NameError: name 'thisdict' is not defined

In [52]:
# The clear() keyword empties the dictionary:

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.clear()
print(thisdict)

{}


### something interesting - shallow copy and deep copy

In [53]:
import numpy as np
a = [1,2,3]
b = a
print(b)
b[-1] = 0
print(a)

[1, 2, 3]
[1, 2, 0]


In [59]:
a = np.array(range(12))
b = a.view()                      # b is a view of a's data, shallow copy
b.shape = 2,6
print(a)
print(b)
print(b is a)
print(b.base is a)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
False
True
1753703151136
1753703151856


In [57]:
b[0,4] = 987456
print(a)

[     0      1      2      3 987456      5      6      7      8      9
     10     11]


In [62]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:,1:3]
print(a)
print(b)
b[0,0] = 6666
print(a)           #slice is also shallow copy

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[   1 6666    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]


In [63]:
a = np.array(range(12))
b = a.copy()                      # deep copy
b.shape = 2,6
print(a)
print(b)
print(b is a)
print(b.base is a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
False
False


In [64]:
b[0,4] = 987456
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
